openapi: 3.0.0
info:
  title: Folio modules API
  version: v2.1.0
  description: Folio modules API used by mod-linked-data

paths: {}

components:
  schemas:
    resourceIndexEvent:
      $ref: folio-modules/search/resourceIndexEvent.json
    resourceIndexEventType:
      $ref: folio-modules/search/resourceIndexEventType.json
    searchResponseTotalOnly:
      $ref: folio-modules/search/searchResponseTotalOnly.json
    settingsSearchResponse:
      $ref: folio-modules/search/settingsSearchResponse.json
    linkedDataInstance:
      $ref: folio-modules/search/linkedDataInstance.json
    linkedDataWork:
      $ref: folio-modules/search/linkedDataWork.json
    instanceIngressEvent:
      $ref: folio-modules/inventory/instanceIngressEvent.json
    sourceRecordDomainEvent:
      $ref: folio-modules/srs/sourceRecordDomainEvent.json
    inventoryInstanceEvent:
      $ref: folio-modules/inventory/inventoryInstanceEvent.json
    inventoryDomainHoldingEvent:
      $ref: folio-modules/inventory/storage/inventoryDomainHoldingEvent.json
    inventoryDomainItemEvent:
      $ref: folio-modules/inventory/storage/inventoryDomainItemEvent.json
