openapi: 3.0.0
info:
  title: Linked Data API
  version: v1
  description: Linked Data service API

paths:
  /reindex:
    put:
      operationId: reindex
      description: Start the process of reindexing of resources in the database
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/full'
      responses:
        '204':
          description: Started the process of reindex
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'

  /resource:
    post:
      operationId: createResource
      description: Create a Resource
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: schema/resourceRequestDto.json
      responses:
        '200':
          description: Created resource
          content:
            application/json:
              schema:
                $ref: schema/resourceResponseDto.json
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'

  /resource/{id}:
    get:
      operationId: getResourceById
      description: Get a resource by id
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Resource as json string
          content:
            application/json:
              schema:
                $ref: schema/resourceResponseDto.json
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '404':
          description: No Resource is found by id
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    put:
      operationId: updateResource
      description: Update a resource by id
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/id'
      requestBody:
        content:
          application/json:
            example: example/resourceRequest.sample
            schema:
              $ref: schema/resourceRequestDto.json
      responses:
        '200':
          description: Updated resource
          content:
            application/json:
              schema:
                $ref: schema/resourceResponseDto.json
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '404':
         description: No resource is found by id
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    delete:
      operationId: deleteResource
      description: Delete a resource by id
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: Resource deleted
        '404':
          description: No resource is found by id
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'

  /resource/{id}/marc:
    get:
      operationId: getResourceMarcViewById
      description: Get a marc view of resource by id
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Marc view of resource as json string
          content:
            application/json:
              schema:
                $ref: schema/resourceMarcViewDto.json
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '404':
          description: No Resource is found by id
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'

  /resource/metadata/{inventoryId}/id:
    get:
      operationId: getResourceIdByResourceInventoryId
      description: Get id of a resource by its inventory id
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/inventoryId'
      responses:
        '200':
          description: Json object with id of a resource
          content:
            application/json:
              schema:
                $ref: schema/resourceIdDto.json
        '404':
          description: No resource id is found by its inventory id

  /resource/check/{inventoryId}/supported:
    get:
      operationId: isSupportedByInventoryId
      description: Check if marc to bib conversion is supported
      parameters:
        - $ref: '#/components/parameters/inventoryId'
      responses:
        '200':
          description: true if marc to bib conversion is supported and false if not supported
          content:
            text/plain:
              schema:
                type: string
                example: true|false
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'

  /resource/preview/{inventoryId}:
    get:
      operationId: getResourcePreviewByInventoryId
      description: Get the preview of a resource
      parameters:
        - $ref: '#/components/parameters/inventoryId'
      responses:
        '200':
          description: Resource as json string
          content:
            application/json:
              schema:
                $ref: schema/resourceResponseDto.json
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'

  /profile:
    get:
      operationId: getProfile
      description: Get profile
      responses:
        '200':
          description: Profile
          content:
            text/plain;charset=utf-8:
              schema:
                type: string
                example: example/profile.sample
        '404':
          description: No profile is found
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'

  /graph/resource/{id}:
    get:
      operationId: getResourceGraphById
      description: Get a resource graph by id
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Resource graph as json string
          content:
            application/json:
              schema:
                $ref: schema/graphDto/resourceGraphDto.json
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '404':
          description: No Resource graph is found by id
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'

components:
  parameters:
    id:
      name: id
      in: path
      required: true
      description: Bibframe resource id
      schema:
        type: integer
        format: int64
    inventoryId:
      name: inventoryId
      in: path
      required: true
      description: Bibframe resource inventory id
      schema:
        type: string
    x-okapi-tenant-header:
      name: x-okapi-tenant
      in: header
      description: X-Okapi-Tenant header value
      schema:
        type: string
    full:
      name: full
      in: query
      required: false
      description: Reindex all records if true, otherwise only not indexed
      schema:
        type: boolean

  schemas:
    errorResponse:
      $ref: schema/error/errors.json

  responses:
    badRequestResponse:
      description: Validation errors
      content:
        application/json:
          example: examples/validationErrorResponse.sample
          schema:
            $ref: "#/components/schemas/errorResponse"
    internalServerErrorResponse:
      description: When unhandled exception occurred during code execution, e.g. NullPointerException
      content:
        application/json:
          example: example/unknownError.sample
          schema:
            $ref: "#/components/schemas/errorResponse"
