openapi: 3.0.0
info:
  title: Linked Data API
  version: v1
  description: Linked Data service API

paths:
  /index:
    post:
      operationId: createIndex
      description: Create an index for all resources in db
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: schema/indexRequest.json
      responses:
        '200':
          description: Created resource index
          content:
            application/json:
              schema:
                $ref: schema/indexResponse.json
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
  /bibframe:
    post:
      operationId: createBibframe
      description: Create a Bibframe resource
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: schema/bibframeRequest.json
      responses:
        '200':
          description: Created Bibframe resource
          content:
            application/json:
              schema:
                $ref: schema/bibframeResponse.json
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    get:
      operationId: getBibframeShortInfoPage
      description: Get page of bibframe short info
      parameters:
        - $ref: '#/components/parameters/type'
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/pageNumber'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          description: Page of bibframe short info as json
          content:
            application/json:
              example: example/bibframeShortInfo.sample
              schema:
                $ref: schema/bibframeShortInfoPage.json
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'

  /bibframe/{id}:
    get:
      operationId: getBibframeById
      description: Get a Bibframe resource by id
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Bibframe as json string
          content:
            application/json:
              schema:
                $ref: schema/bibframeResponse.json
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '404':
          description: No Bibframe is found by id
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    put:
      operationId: updateBibframe
      description: Update a Bibframe resource by id
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/id'
      requestBody:
        content:
          application/json:
            example: example/bibframeRequest.sample
            schema:
              $ref: schema/bibframeRequest.json
      responses:
        '200':
          description: Updated Bibframe resource
          content:
            application/json:
              schema:
                $ref: schema/bibframeResponse.json
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '404':
          description: No bibframe is found by id
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    delete:
      operationId: deleteBibframe
      description: Delete a Bibframe resource by id
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: Bibframe resource deleted
        '404':
          description: No bibframe is found by id
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'

  /bibframe2:
    post:
      operationId: createBibframe2
      description: Create a Bibframe 2.0 resource
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
      requestBody:
        content:
          application/json:
            schema:
              $ref: schema/b2/bibframe2Request.json
      responses:
        '200':
          description: Created Bibframe 2.0 resource
          content:
            application/json:
              schema:
                $ref: schema/b2/bibframe2Response.json
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    get:
      operationId: getBibframe2ShortInfoPage
      description: Get page of bibframe 2.0 short info
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/pageNumber'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          description: Page of bibframe short info as json
          content:
            application/json:
              example: example/bibframeShortInfo.sample
              schema:
                $ref: schema/bibframeShortInfoPage.json
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'

  /bibframe2/{id}:
    get:
      operationId: getBibframe2ById
      description: Get a Bibframe 2.0 resource by id
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Bibframe 2.0 as json string
          content:
            application/json:
              schema:
                $ref: schema/b2/bibframe2Response.json
        '400':
            $ref: '#/components/responses/badRequestResponse'
        '404':
          description: No Bibframe is found by id
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    put:
      operationId: updateBibframe2
      description: Update a Bibframe 2.0 resource by id
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/id'
      requestBody:
        content:
          application/json:
            example: example/b2/bibframe2Request.sample
            schema:
              $ref: schema/b2/bibframe2Request.json
      responses:
        '200':
          description: Updated Bibframe resource
          content:
            application/json:
              schema:
                $ref: schema/b2/bibframe2Response.json
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '404':
          description: No bibframe is found by id
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    delete:
      operationId: deleteBibframe2
      description: Delete a Bibframe 2.0 resource by id
      parameters:
        - $ref: '#/components/parameters/x-okapi-tenant-header'
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: Bibframe resource deleted
        '404':
          description: No bibframe is found by id
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'

components:
  parameters:
    id:
      name: id
      in: path
      required: true
      description: Bibframe resource id
      schema:
        type: integer
        format: int64
    x-okapi-tenant-header:
      name: x-okapi-tenant
      in: header
      description: X-Okapi-Tenant header value
      schema:
        type: string
    pageNumber:
      name: pageNumber
      in: query
      required: false
      description: Page number for paginated endpoint, default is 0
      schema:
        type: integer
    pageSize:
      name: pageSize
      in: query
      required: false
      description: Page size for paginated endpoint, default is 100
      schema:
        type: integer
    type:
      name: type
      in: query
      required: true
      description: 'Bibframe resource type, for example: http://bibfra.me/vocab/marc/Monograph'
      example: 'http://bibfra.me/vocab/marc/Monograph'
      schema:
        type: string

  schemas:
    errorResponse:
      $ref: schema/errors.json

  responses:
    badRequestResponse:
      description: Validation errors
      content:
        application/json:
          example: examples/validationErrorResponse.sample
          schema:
            $ref: "#/components/schemas/errorResponse"
    internalServerErrorResponse:
      description: When unhandled exception occurred during code execution, e.g. NullPointerException
      content:
        application/json:
          example: example/unknownError.sample
          schema:
            $ref: "#/components/schemas/errorResponse"
